import type { Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { ReactNode } from "react";
import NavBreadcrumbs from "@/components/nav-breadcrumbs";
import { auth } from "@/lib/auth";
import { notFound } from "next/navigation";
import { findUserByEmail, prisma } from "@/lib/prisma";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  params: Promise<{ lng: string; orgId: string }>;
  children: ReactNode;
};

export default async function RootLayout({ children, params }: Props) {
  const { orgId } = await params;
  const data = await auth.getSession();

  if (!data?.user?.email) {
    notFound();
  }

  const user = await findUserByEmail(data.user.email);

  if (!user) {
    notFound();
  }

  if (!user.currentOrg) {
    await prisma.user.update({
      where: {
        id: user.id,
      },
      data: {
        currentOrg: orgId,
      },
    });
  }

  if (user.currentOrg !== orgId) {
    await prisma.user.update({
      where: {
        id: user.id,
      },
      data: {
        currentOrg: orgId,
      },
    });
  }

  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
          <div className="flex items-center gap-2 px-4">
            <SidebarTrigger className="-ml-1" />
            <Separator orientation="vertical" className="mr-2 h-4" />
            <NavBreadcrumbs />
          </div>
        </header>
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}
